DROP TABLE IF EXISTS MENUS;

CREATE TABLE MENUS (
	MENU_ID	varchar(6)	NOT NULL,
	MENU_NM	varchar(100)	NULL,
	MENU_PID	varchar(6)	NULL,
	MENU_URL	varchar(255)	NULL,
	MENU_ICON	varchar(255)	NULL,
	DISPLAY_NO	int	NOT NULL	DEFAULT 0,
	DISPLAY_YN	varchar(1)	NOT NULL	DEFAULT 'Y',
	USE_YN	varchar(1)	NOT NULL	DEFAULT 'Y'
);

ALTER TABLE MENUS ADD CONSTRAINT PK_MENUS PRIMARY KEY (
	MENU_ID
);

-- INSERT INTO MENUS
-- (MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
-- VALUES('MN1001', 'Dashboard', '000000', 'material/Dashboard', 'home', 1, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN1002', 'Typography', '000000', 'material/typography', 'text_fields', 2, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN1003', 'Helper Classes', '000000', 'material/helper-classes', 'layers', 3, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN1004', 'Widgets', '000000', NULL, 'widgets', 4, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN1005', 'User Interface (UI)', '000000', NULL, 'swap_calls', 5, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN1006', 'Forms', '000000', NULL, 'assignment', 6, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN1007', 'Table', '000000', NULL, 'view_list', 7, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN1008', 'Medias', '000000', NULL, 'perm_media', 8, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN1009', 'Charts', '000000', NULL, 'pie_chart', 9, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN1010', 'Pages Example', '000000', NULL, 'content_copy', 10, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN1011', 'Map', '000000', NULL, 'map', 11, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2001', 'Cards', 'MN1004', NULL, NULL, 1, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2002', 'Infobox', 'MN1004', NULL, NULL, 2, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2101', 'Alerts', 'MN1005', 'material/ui/alerts', NULL, 1, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2102', 'Animation', 'MN1005', 'material/ui/animations', NULL, 2, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2103', 'Badges', 'MN1005', 'material/ui/badges', NULL, 3, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2104', 'Breadcrumbs', 'MN1005', 'material/ui/breadcrumbs', NULL, 4, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2105', 'Button', 'MN1005', 'material/ui/buttons', NULL, 5, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2106', 'Collapse', 'MN1005', 'material/ui/collapse', NULL, 6, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2107', 'Color', 'MN1005', 'material/ui/colors', NULL, 7, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2108', 'Dialogs', 'MN1005', 'material/ui/dialogs', NULL, 8, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2109', 'ICon', 'MN1005', 'material/ui/icons', NULL, 9, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2110', 'Lable', 'MN1005', 'material/ui/labels', NULL, 10, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2111', 'List Group', 'MN1005', 'material/ui/list-group', NULL, 11, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2112', 'Media Object', 'MN1005', 'material/ui/media-object', NULL, 12, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2113', 'Modals', 'MN1005', 'material/ui/modals', NULL, 13, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2114', 'Notification', 'MN1005', 'material/ui/notifications', NULL, 14, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2115', 'Paging', 'MN1005', 'material/ui/pagination', NULL, 15, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2116', 'Loaders', 'MN1005', 'material/ui/preloaders', NULL, 16, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2117', 'Progress Bars', 'MN1005', 'material/ui/progressbars', NULL, 17, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2118', 'Range Sliders', 'MN1005', 'material/ui/range-sliders', NULL, 18, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2119', 'Sortable & Nestable', 'MN1005', 'material/ui/sortable-nestable', NULL, 19, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2120', 'Tabs', 'MN1005', 'material/ui/tabs', NULL, 20, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2121', 'Thumbnails', 'MN1005', 'material/ui/thumbnails', NULL, 21, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2122', 'Tolltips', 'MN1005', 'material/ui/tooltips-popovers', NULL, 22, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2123', 'Waves', 'MN1005', 'material/ui/waves', NULL, 23, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2201', 'Basic From', 'MN1006', 'material/forms/basic-form-elements', NULL, 1, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2202', 'Advanced Form', 'MN1006', 'material/forms/advanced-form-elements', NULL, 2, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2203', 'Form Ex', 'MN1006', 'material/forms/form-examples', NULL, 3, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2204', 'Form Validation', 'MN1006', 'material/forms/form-validation', NULL, 4, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2205', 'Form Wizard', 'MN1006', 'material/forms/form-wizard', NULL, 5, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2206', 'Editors', 'MN1006', 'material/forms/editors', NULL, 6, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2301', 'Normal Tables', 'MN1007', 'material/tables/normal-tables', NULL, 1, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2302', 'jQuery Datatable', 'MN1007', 'material/tables/jquery-datatable', NULL, 2, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2303', 'Editable Table', 'MN1007', 'material/tables/editable-table', NULL, 3, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2401', 'Image Gallery', 'MN1008', 'material/medias/image-gallery', NULL, 1, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2402', 'Image Sliders', 'MN1008', 'material/medias/carousel', NULL, 2, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2501', 'Morris', 'MN1009', 'material/charts/morris', NULL, 1, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2502', 'Flot', 'MN1009', 'material/charts/flot', NULL, 2, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2503', 'ChartJS', 'MN1009', 'material/charts/chartjs', NULL, 3, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2504', 'Sparkline', 'MN1009', 'material/charts/sparkline', NULL, 4, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2505', 'Jquery Knob', 'MN1009', 'material/charts/jquery-knob', NULL, 5, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2601', 'Profile', 'MN1010', 'material/examples/profile', NULL, 1, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2602', 'Login', 'MN1010', 'material/examples/sign-in', NULL, 2, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2603', 'Sign Up', 'MN1010', 'material/examples/sign-up', NULL, 3, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2604', 'Forgot Password', 'MN1010', 'material/examples/forgot-password', NULL, 4, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2605', '403 Error', 'MN1010', 'material/examples/403', NULL, 5, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2606', '404 Error', 'MN1010', 'material/examples/404', NULL, 6, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2607', '500 Error', 'MN1010', 'material/examples/500', NULL, 7, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2600', 'Blank', 'MN1010', 'material/examples/blank', NULL, 0, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2701', 'Google Map', 'MN1011', 'material/maps/google', NULL, 1, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2702', 'Yandex Map', 'MN1011', 'material/maps/yandex', NULL, 2, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2703', 'jVector Map', 'MN1011', 'material/maps/jvectormap', NULL, 3, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN3001', 'Basic', 'MN2001', 'material/widgets/cards/basic', NULL, 1, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN3002', 'Colored', 'MN2001', 'material/widgets/cards/colored', NULL, 2, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN3003', 'No Header', 'MN2001', 'material/widgets/cards/no-header', NULL, 3, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN3011', 'Infobox-1', 'MN2002', 'material/widgets/infobox/infobox-1', NULL, 1, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN3012', 'Infobox-2', 'MN2002', 'material/widgets/infobox/infobox-2', NULL, 2, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN3013', 'Infobox-3', 'MN2002', 'material/widgets/infobox/infobox-3', NULL, 3, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN3014', 'Infobox-4', 'MN2002', 'material/widgets/infobox/infobox-4', NULL, 4, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN3015', 'Infobox-5', 'MN2002', 'material/widgets/infobox/infobox-5', NULL, 5, 'Y', 'Y');

-- INSERT INTO MENUS
-- (MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
-- VALUES('MN4000', 'Changelogs', '000000', 'material/about/changelogs', 'update', 5, 'Y', 'Y');

INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN4000', 'About', '000000', NULL, 'update', 5, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN4100', 'Browser Spport', 'MN4000', 'material/about/browser-support', NULL, 1, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN4101', 'Dependencies', 'MN4000', 'material/about/dependencies', NULL, 2, 'Y', 'Y');
INSERT INTO MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN4102', 'Plugins', 'MN4000', 'material/about/plugins', NULL, 3, 'Y', 'Y');
