DROP TABLE IF EXISTS MENUS;

CREATE TABLE MENUS (
	MENU_ID	varchar(6)	NOT NULL,
	MENU_NM	varchar(100)	NULL,
	MENU_PID	varchar(6)	NULL,
	MENU_URL	varchar(255)	NULL,
	MENU_ICON	varchar(255)	NULL,
	DISPLAY_NO	int	NOT NULL	DEFAULT 0,
	DISPLAY_YN	varchar(1)	NOT NULL	DEFAULT 'Y',
	USE_YN	varchar(1)	NOT NULL	DEFAULT 'Y'
);

ALTER TABLE MENUS ADD CONSTRAINT PK_MENUS PRIMARY KEY (
	MENU_ID
);

-- INSERT INTO material.MENUS
-- (MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
-- VALUES('MN1001', 'Dashboard', '000000', '/Dashboard.do', 'home', 1, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN1002', 'Typography', '000000', '/typography.do', 'text_fields', 2, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN1003', 'Helper Classes', '000000', '/helper-classes.do', 'layers', 3, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN1004', 'Widgets', '000000', NULL, 'widgets', 4, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN1005', 'User Interface (UI)', '000000', NULL, 'swap_calls', 5, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN1006', 'Forms', '000000', NULL, 'assignment', 6, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN1007', 'Table', '000000', NULL, 'view_list', 7, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN1008', 'Medias', '000000', NULL, 'perm_media', 8, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN1009', 'Charts', '000000', NULL, 'pie_chart', 9, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN1010', 'Pages Example', '000000', NULL, 'content_copy', 10, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN1011', 'Map', '000000', NULL, 'map', 11, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2001', 'Cards', 'MN1004', NULL, NULL, 1, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2002', 'Infobox', 'MN1004', NULL, NULL, 2, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2101', 'Alerts', 'MN1005', '/ui/alerts.do', NULL, 1, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2102', 'Animation', 'MN1005', '/ui/animations.do', NULL, 2, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2103', 'Badges', 'MN1005', '/ui/badges.do', NULL, 3, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2104', 'Breadcrumbs', 'MN1005', '/ui/breadcrumbs.do', NULL, 4, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2105', 'Button', 'MN1005', '/ui/buttons.do', NULL, 5, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2106', 'Collapse', 'MN1005', '/ui/collapse.do', NULL, 6, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2107', 'Color', 'MN1005', '/ui/colors.do', NULL, 7, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2108', 'Dialogs', 'MN1005', '/ui/dialogs.do', NULL, 8, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2109', 'ICon', 'MN1005', '/ui/icons.do', NULL, 9, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2110', 'Lable', 'MN1005', '/ui/labels.do', NULL, 10, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2111', 'List Group', 'MN1005', '/ui/list-group.do', NULL, 11, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2112', 'Media Object', 'MN1005', '/ui/media-object.do', NULL, 12, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2113', 'Modals', 'MN1005', '/ui/modals.do', NULL, 13, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2114', 'Notification', 'MN1005', '/ui/notifications.do', NULL, 14, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2115', 'Paging', 'MN1005', '/ui/pagination.do', NULL, 15, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2116', 'Loaders', 'MN1005', '/ui/preloaders.do', NULL, 16, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2117', 'Progress Bars', 'MN1005', '/ui/progressbars.do', NULL, 17, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2118', 'Range Sliders', 'MN1005', '/ui/range-sliders.do', NULL, 18, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2119', 'Sortable & Nestable', 'MN1005', '/ui/sortable-nestable.do', NULL, 19, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2120', 'Tabs', 'MN1005', '/ui/tabs.do', NULL, 20, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2121', 'Thumbnails', 'MN1005', '/ui/thumbnails.do', NULL, 21, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2122', 'Tolltips', 'MN1005', '/ui/tooltips-popovers.do', NULL, 22, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2123', 'Waves', 'MN1005', '/ui/waves.do', NULL, 23, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2201', 'Basic From', 'MN1006', '/forms/basic-form-elements.do', NULL, 1, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2202', 'Advanced Form', 'MN1006', '/forms/advanced-form-elements.do', NULL, 2, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2203', 'Form Ex', 'MN1006', '/forms/form-examples.do', NULL, 3, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2204', 'Form Validation', 'MN1006', '/forms/form-validation.do', NULL, 4, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2205', 'Form Wizard', 'MN1006', '/forms/form-wizard.do', NULL, 5, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2206', 'Editors', 'MN1006', '/forms/editors.do', NULL, 6, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2301', 'Normal Tables', 'MN1007', '/tables/normal-tables.do', NULL, 1, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2302', 'jQuery Datatable', 'MN1007', '/tables/jquery-datatable.do', NULL, 2, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2303', 'Editable Table', 'MN1007', '/tables/editable-table.do', NULL, 3, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2401', 'Image Gallery', 'MN1008', '/medias/image-gallery.do', NULL, 1, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2402', 'Image Sliders', 'MN1008', '/medias/carousel.do', NULL, 2, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2501', 'Morris', 'MN1009', '/charts/morris.do', NULL, 1, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2502', 'Flot', 'MN1009', '/charts/flot.do', NULL, 2, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2503', 'ChartJS', 'MN1009', '/charts/chartjs.do', NULL, 3, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2504', 'Sparkline', 'MN1009', '/charts/sparkline.do', NULL, 4, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2505', 'Jquery Knob', 'MN1009', '/charts/jquery-knob.do', NULL, 5, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2601', 'Profile', 'MN1010', '/examples/profile.do', NULL, 1, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2602', 'Login', 'MN1010', '/examples/sign-in.do', NULL, 2, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2603', 'Sign Up', 'MN1010', '/examples/sign-up.do', NULL, 3, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2604', 'Forgot Password', 'MN1010', '/examples/forgot-password.do', NULL, 4, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2605', '403 Error', 'MN1010', '/examples/code403.do', NULL, 5, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2606', '404 Error', 'MN1010', '/examples/code404.do', NULL, 6, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2607', '500 Error', 'MN1010', '/examples/code500.do', NULL, 7, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2701', 'Google Map', 'MN1011', '/maps/google.do', NULL, 1, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2702', 'Yandex Map', 'MN1011', '/maps/yandex.do', NULL, 2, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN2703', 'jVector Map', 'MN1011', '/maps/jvectormap.do', NULL, 3, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN3001', 'Basic', 'MN2001', '/widgets/cards/basic.do', NULL, 1, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN3002', 'Colored', 'MN2001', '/widgets/cards/colored.do', NULL, 2, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN3003', 'No Header', 'MN2001', '/widgets/cards/no-header.do', NULL, 3, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN3011', 'Infobox-1', 'MN2002', '/widgets/infobox/infobox-1.do', NULL, 1, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN3012', 'Infobox-2', 'MN2002', '/widgets/infobox/infobox-2.do', NULL, 2, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN3013', 'Infobox-3', 'MN2002', '/widgets/infobox/infobox-3.do', NULL, 3, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN3014', 'Infobox-4', 'MN2002', '/widgets/infobox/infobox-4.do', NULL, 4, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN3015', 'Infobox-5', 'MN2002', '/widgets/infobox/infobox-5.do', NULL, 5, 'Y', 'Y');
INSERT INTO material.MENUS
(MENU_ID, MENU_NM, MENU_PID, MENU_URL, MENU_ICON, DISPLAY_NO, DISPLAY_YN, USE_YN)
VALUES('MN4000', 'Changelogs', '000000', '/changelogs.do', 'update', 5, 'Y', 'Y');
